/* parser generated by jison 0.4.15 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var parser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,6],$V1=[1,7],$V2=[9,11,19],$V3=[9,11,19,22],$V4=[5,17,18,20,21,31,32,33,34,35,36,38,39],$V5=[1,16],$V6=[1,17],$V7=[1,34],$V8=[1,35],$V9=[1,30],$Va=[1,31],$Vb=[1,32],$Vc=[1,28],$Vd=[1,29],$Ve=[1,38],$Vf=[20,21],$Vg=[17,18,20,21,31,32],$Vh=[17,18,20,21,31,32,34,35,36,38,39],$Vi=[17,18,20,21,31,32,33,34,35,36,38,39],$Vj=[9,11,17,18,19,20,21,22,31,32,34,35,36,38,39],$Vk=[17,18,31,32],$Vl=[17,18,31,32,33];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"file":3,"component":4,"EOF":5,"uniquetag":6,"tagbegin":7,"tagselfclose":8,"tagend":9,"tagclose":10,"ENDTAG":11,"tagsandtext":12,"tag":13,"loop":14,"tagstart":15,"properties":16,"BEGINLOWERTAG":17,"BEGINCAMELTAG":18,"SELFCLOSE":19,"CLOSECAMELTAG":20,"CLOSELOWERTAG":21,"PROPERTYDECLARATION":22,"string":23,"STRING":24,"variable":25,"tags":26,"innertext":27,"tagsintag":28,"loopstart":29,"loopend":30,"MUSTACHESECTION":31,"MUSTACHEINVERTED":32,"MUSTACHEEND":33,"MUSTACHESIMPLEVAR":34,"MUSTACHECOMPLEXVAR":35,"MUSTACHETHIS":36,"longtext":37,"TEXT":38,"SINGLECHAR":39,"quotedlongtext":40,"textfragment":41,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",9:"tagend",11:"ENDTAG",17:"BEGINLOWERTAG",18:"BEGINCAMELTAG",19:"SELFCLOSE",20:"CLOSECAMELTAG",21:"CLOSELOWERTAG",22:"PROPERTYDECLARATION",24:"STRING",31:"MUSTACHESECTION",32:"MUSTACHEINVERTED",33:"MUSTACHEEND",34:"MUSTACHESIMPLEVAR",35:"MUSTACHECOMPLEXVAR",36:"MUSTACHETHIS",38:"TEXT",39:"SINGLECHAR"},
productions_: [0,[3,2],[4,1],[6,2],[6,3],[6,4],[13,1],[13,1],[7,2],[7,1],[15,1],[15,1],[8,1],[10,1],[10,1],[16,2],[16,3],[23,1],[23,1],[26,1],[26,2],[12,1],[12,1],[12,2],[12,2],[12,3],[28,1],[28,2],[28,3],[14,3],[29,1],[29,1],[30,1],[25,1],[25,1],[25,1],[37,1],[37,1],[37,2],[37,2],[40,1],[41,1],[41,2],[41,2],[27,1],[27,1],[27,2]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:

          var contains = function(x){return $$[$0-1].indexOf(x) > -1},
            loopfunc = "function(a){return Array.isArray(a) && a || !!a && [a] || []}",
            negatefunc = "function(a){return (a==null || a.length===0) && [a] || []}";
          return ("React.createClass({\n" +
          (contains("this.loop(") 
              ? "  loop: " + loopfunc + ",\n"
              : "") +
          (contains("this.negate(") 
              ? "  negate: " + negatefunc + ",\n"
              : "") +
          "  render: function(){\n" +
          "    return "+$$[$0-1]+";\n" +
          "  }\n" +
          "});");
        
break;
case 3: case 38: case 39:
this.$ = $$[$0-1]+$$[$0]
break;
case 4:
this.$ = $$[$0-2] + $$[$0-1] + $$[$0]
break;
case 5:
this.$ = $$[$0-3] + ', ' + $$[$0-1] + $$[$0]
break;
case 8:
this.$ = 'React.createElement(' + $$[$0-1] + ', {' + $$[$0] + '}'
break;
case 9:
this.$ = 'React.createElement(' + $$[$0] + ', null'
break;
case 10:
this.$ = '"'+$$[$0]+'"'
break;
case 11: case 36: case 37:
this.$ = $$[$0]
break;
case 12: case 13: case 14:
this.$ = ')'
break;
case 15:
this.$ = '"' + $$[$0-1] + '": ' + $$[$0]
break;
case 16:
this.$ = ', "' + $$[$0-1] + '": ' + $$[$0]
break;
case 17:
this.$ = JSON.stringify(yytext)
break;
case 20:
this.$ = $$[$0-1]+','+$$[$0]
break;
case 23: case 24:
this.$ = $$[$0-1] + ', ' + $$[$0]
break;
case 25: case 28:
this.$ = [$$[$0-2],$$[$0-1],$$[$0]].join(', ')
break;
case 27:
this.$ = $$[$0-1]+', '+$$[$0]
break;
case 29:
this.$ = $$[$0-2]+$$[$0-1]+$$[$0]
break;
case 30:
this.$ = 'this.loop(context.'+yytext+').map(function(context){return '
break;
case 31:
this.$ = 'this.negate('+$$[$0]+').map(function(matched){return ';
break;
case 32:
this.$ = '})'
break;
case 33:
this.$ = 'context.' + yytext
break;
case 34:
this.$ = 'context["' + yytext + '"]'
break;
case 35:
this.$ = 'context'
break;
case 40:
this.$ = JSON.stringify($$[$0])
break;
case 42:
this.$ =$$[$0-1]+'+'+$$[$0]
break;
case 43:
this.$ = $$[$0-1]+'+'+$$[$0]
break;
case 46:
this.$ = $$[$0-1] + ' + ' + $$[$0]
break;
}
},
table: [{3:1,4:2,6:3,7:4,15:5,17:$V0,18:$V1},{1:[3]},{5:[1,8]},{5:[2,2]},{8:9,9:[1,10],11:[1,11],19:[1,12]},o($V2,[2,9],{16:13,22:[1,14]}),o($V3,[2,10]),o($V3,[2,11]),{1:[2,1]},o($V4,[2,3]),{10:15,20:$V5,21:$V6},{6:26,7:4,12:18,13:23,14:27,15:5,17:$V0,18:$V1,25:25,27:19,28:20,29:33,31:$V7,32:$V8,34:$V9,35:$Va,36:$Vb,37:24,38:$Vc,39:$Vd,40:21,41:22},o($V4,[2,12]),o($V2,[2,8],{22:[1,36]}),{23:37,24:$Ve,25:39,34:$V9,35:$Va,36:$Vb},o($V4,[2,4]),o($V4,[2,13]),o($V4,[2,14]),{10:40,20:$V5,21:$V6},o($Vf,[2,21],{7:4,15:5,13:23,6:26,14:27,29:33,28:41,17:$V0,18:$V1,31:$V7,32:$V8}),o($Vf,[2,22],{7:4,15:5,40:21,41:22,37:24,25:25,6:26,14:27,29:33,27:42,13:43,17:$V0,18:$V1,31:$V7,32:$V8,34:$V9,35:$Va,36:$Vb,38:$Vc,39:$Vd}),o($Vg,[2,44],{25:44,34:$V9,35:$Va,36:$Vb}),o($Vg,[2,45],{37:24,40:45,25:46,34:$V9,35:$Va,36:$Vb,38:$Vc,39:$Vd}),o($Vh,[2,26]),o([17,18,20,21,31,32,34,35,36],[2,40],{38:[1,47],39:[1,48]}),o($Vh,[2,41]),o($Vi,[2,6]),o($Vi,[2,7]),o($Vh,[2,36]),o($Vh,[2,37]),o($Vj,[2,33]),o($Vj,[2,34]),o($Vj,[2,35]),{6:26,7:4,13:50,14:27,15:5,17:$V0,18:$V1,26:49,29:33,31:$V7,32:$V8},o($Vk,[2,30]),o($Vk,[2,31]),{23:51,24:$Ve,25:39,34:$V9,35:$Va,36:$Vb},o($V3,[2,15]),o($V3,[2,17]),o($V3,[2,18]),o($V4,[2,5]),o($Vf,[2,23],{7:4,15:5,40:21,41:22,37:24,25:25,6:26,14:27,29:33,13:43,27:52,17:$V0,18:$V1,31:$V7,32:$V8,34:$V9,35:$Va,36:$Vb,38:$Vc,39:$Vd}),o($Vf,[2,24],{7:4,15:5,6:26,14:27,29:33,13:53,17:$V0,18:$V1,31:$V7,32:$V8}),o($Vh,[2,27]),o($Vh,[2,42]),o($Vg,[2,46]),o($Vh,[2,43]),o($Vh,[2,38]),o($Vh,[2,39]),{6:26,7:4,13:55,14:27,15:5,17:$V0,18:$V1,29:33,30:54,31:$V7,32:$V8,33:[1,56]},o($Vl,[2,19]),o($V3,[2,16]),o($Vf,[2,25],{7:4,15:5,6:26,14:27,29:33,13:53,17:$V0,18:$V1,31:$V7,32:$V8}),o($Vh,[2,28]),o($Vi,[2,29]),o($Vl,[2,20]),o($Vi,[2,32])],
defaultActions: {3:[2,2],8:[2,1]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        throw new Error(str);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        function lex() {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        }
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex() {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:return 21;
break;
case 1:return 20;
break;
case 2:yy_.yytext = yy_.yytext.substr(1); this.begin('intag'); return 17;
break;
case 3:yy_.yytext = yy_.yytext.substr(1); this.begin('intag'); return 18;
break;
case 4:this.popState(); return 19;
break;
case 5:this.popState(); return 11;
break;
case 6:yy_.yytext = yy_.yytext.substr(0,yy_.yyleng-1); return 22;
break;
case 7:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return 24;
break;
case 8:/*ignore whitespaces in tags*/
break;
case 9:yy_.yytext = yy_.yytext.substr(3, yy_.yyleng-5).trim(); return 31;
break;
case 10:yy_.yytext = yy_.yytext.substr(3, yy_.yyleng-5).trim(); return 33;
break;
case 11:yy_.yytext = yy_.yytext.substr(2, yy_.yyleng-4).trim(); return 36;
break;
case 12:yy_.yytext = yy_.yytext.substr(2, yy_.yyleng-4).trim(); return 34;
break;
case 13:yy_.yytext = yy_.yytext.substr(2, yy_.yyleng-4).trim(); return 35;
break;
case 14:return 38;
break;
case 15:return 5;
break;
case 16:return 39;
break;
}
},
rules: [/^(?:<\/([a-z]+[0-9]*)>)/,/^(?:<\/([A-Z][a-zA-Z]*[0-9]*)>)/,/^(?:<([a-z]+[0-9]*))/,/^(?:<([A-Z][a-zA-Z]*[0-9]*))/,/^(?:\/>)/,/^(?:>)/,/^(?:([a-z]+[0-9]*)=)/,/^(?:"[^"]*")/,/^(?:\s+)/,/^(?:\{\{#\s*[a-z]*\s*\}\})/,/^(?:\{\{\/\s*[a-z]*\s*\}\})/,/^(?:\{\{\s*\.\s*\}\})/,/^(?:\{\{\s*[a-zA-Z][a-zA-Z0-9_]+\s*\}\})/,/^(?:\{\{\s*([\w /\-.]+)\s*\}\})/,/^(?:[^<>{}]+)/,/^(?:$)/,/^(?:.)/],
conditions: {"intag":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],"inclusive":true},"INITIAL":{"rules":[0,1,2,3,9,10,11,12,13,14,15,16],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = parser;
exports.Parser = parser.Parser;
exports.parse = function () { return parser.parse.apply(parser, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}